### ISSUE TITLE
Instruction issues

### ISSUE THREAD

**Issue by d3n8it** [Lifailon/bash-api-server#1]
Thank you very much for the script and instructions!

I installed it on my server and ran into problems.

**Problem 1.**
There is a typo in 'a2ensite api.confs' in step 5. Should be 'a2ensite api.conf'. Right?

With this fix, the script worked for me!

**Comment by Lifailon** [comment]
Good day! Yes, you are right! this is a typo, how it will be possible to be at the computer, I will correct it
